### ISSUE TITLE
Kapitel 5.1 - Inhaltlich 

### ISSUE THREAD

**Issue by jnnkls** [FHA-SWE/Tasks#17]
Aufwand: 3h

**Comment by lewoGames** [comment]
Hab alle änderungen bzgl. der Kommentare im PDF sowie im Google Doc vorgenommen welche die Aktivitätsdiagramme betrafen.

**Comment by jnnkls** [comment]
@jojo2904 review?

**Comment by jnsmr** [comment]
Bin mit 5.1 fertig
@lewoGames 
Bei dem Diagramm u09 die E-Mail bestätigung bitte noch rausnehmen
Und bei u01.1 verschwinden beide Diagramme wenn ich das annehme
