### ISSUE TITLE
Kapitel 5 - Finale Kleinlichkeiten 

### ISSUE THREAD

**Issue by jnnkls** [FHA-SWE/Tasks#22]

**Comment by lewoGames** [comment]
- Aktivitätsdiagramme angepasst/aktualisiert
- Mockups dementsprechend aktualisiert
- Abbildungstitel der Mockups angepasst

**Comment by jnsmr** [comment]
- Mockups Beschreibung hinzugefügt
- bei u02 waren die Unterschriften der Diagramme verrutscht
- 5.1 reviewed
